FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase
  Passive:
    transitions: 
      FixStand: LT + up.on_pressed
    mode: [ # motor mode
      10,10,10,10,10,10,
      10,10,10,10,
      1,1,
      1,1,1,1,
      1,1,1,1
    ]
    kd: [
      5,5,6,5,5,6,
      5,5,5,
      0, # reserved
      2,2,
      2,2,2,2,
      2,2,2,2, 
    ]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    kp: [
      200, 200, 300, 200, 200, 300,
      200, 200, 200, 
      0, # reserved
      40, 40,
      100, 50, 50, 50,
      100, 50, 50, 50,
    ]
    kd: [
      5,5,6,5,5,6,
      5,5,5,
      0, # reserved
      2,2,
      2,2,2,2,
      2,2,2,2,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ 0, -0.28, 0.79, 0, -0.28, 0.79,
        0, 0, 0,
        0, # reserved
        -0.52, -0.52, 
        0.2, 0, 0, 0.32,
        0.2, 0, 0, 0.32,
      ]
    ]
  Velocity:
    transitions: 
      Passive: LT + B.on_pressed
    policy_dir: ../../../logs/rsl_rl/unitree_h1_velocity